apiVersion: apps/v1
kind: Deployment
metadata:
  name: passenger-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: passenger-api
  template:
    metadata:
      labels:
        app: passenger-api
    spec:
      containers:
        - name: passenger-api
          image: "passenger-api:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
#      imagePullSecrets:
#        - name: "{{ .Values.image.pullSecret }}"